services:
  nodejs:
    build:
      context: .
      args:
        - NODE_VERSION=${NODE_VERSION}
        - APK_BUILD_DEPS=${APK_BUILD_DEPS}
        - APK_RUN_DEPS=${APK_RUN_DEPS}

    restart: "no"

    stop_grace_period: 30s

    cpu_shares: 2048
    # mem_limit: 256m

    env_file: .env

    tty: true

    volumes:
      - type: bind
        source: ./_data
        target: /data
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'
